version: 2

project_name: v7y

before:
  hooks:
    - rm -rf ./dist
    - go mod tidy
    - git push
    - git push --tags

builds:
  - id: v7y
    env:
      - CGO_ENABLED=0
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - -s
      - -w
      - -X main.version={{.Version}}
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    binary: v7y

archives:
  - formats: [ "tar.gz" ]
    name_template: "{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    ids:
      - v7y

release:
  prerelease: auto

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"
  algorithm: sha256

brews:
  -
    name: v7y
    repository:
      owner: sikalabsx
      name: homebrew-tap
    skip_upload: auto
    homepage: https://github.com/sikalabsx/v7y
    url_template: "https://github.com/sikalabsx/v7y/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    directory: Formula
    caveats: "How to use this binary: https://github.com/sikalabsx/v7y"
    description: "v7y"
    install: |
      bin.install "v7y"
    test: |
      system "#{bin}/v7y --version"

dockers:
    -
      goos: linux
      goarch: amd64
      image_templates:
        - "ghcr.io/sikalabsx/v7y:{{ .Tag }}"
      dockerfile: Dockerfile.goreleaser
      ids:
        - v7y
      build_flag_templates:
        - "--platform=linux/amd64"
        - "--label=org.opencontainers.image.created={{.Date}}"
        - "--label=org.opencontainers.image.title={{.ProjectName}}"
        - "--label=org.opencontainers.image.revision={{.FullCommit}}"
        - "--label=org.opencontainers.image.version={{.Version}}"
        - "--label=org.label-schema.schema-version=1.0"
        - "--label=org.label-schema.version={{.Version}}"
        - "--label=org.label-schema.name={{.ProjectName}}"
        - "--label=com.github.actions.name={{.ProjectName}}"
        - "--label=repository=https://github.com/sikalabsx/v7y"
        - "--label=maintainer=Ondrej Sika <ondrej@sika.io>"
    - goos: linux
      goarch: arm64
      image_templates:
        - "ghcr.io/sikalabsx/v7y:{{ .Tag }}-arm64v8"
      dockerfile: Dockerfile.goreleaser.arm64v8
      ids:
        - v7y
      build_flag_templates:
        - "--platform=linux/arm64"
        - "--label=org.opencontainers.image.created={{.Date}}"
        - "--label=org.opencontainers.image.title={{.ProjectName}}"
        - "--label=org.opencontainers.image.revision={{.FullCommit}}"
        - "--label=org.opencontainers.image.version={{.Version}}"
        - "--label=org.label-schema.schema-version=1.0"
        - "--label=org.label-schema.version={{.Version}}"
        - "--label=org.label-schema.name={{.ProjectName}}"
        - "--label=com.github.actions.name={{.ProjectName}}"
        - "--label=repository=https://github.com/sikalabsx/v7y"
        - "--label=maintainer=Ondrej Sika <ondrej@sika.io>"
